name: Build and Test Qt Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.6.0'
        archives: 'qttools'

    - name: Configure Project (qmake)
      run: |
        mkdir build
        cd build
        qmake ../TicTacToe_With_Tests.pro

    - name: Build Project (make/nmake)
      shell: bash
      run: |
        cd build
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          nmake
        else
          make
        fi

    - name: Run Tests
      shell: bash
      run: |
        cd build/tests
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          ./release/tests.exe
        else
          ./tests
        fi