name: Build and Test Qt Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Job for Linux
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install aqtinstall
      - name: Install Linux build dependencies
        run: sudo apt-get update && sudo apt-get install -y libgl1-mesa-dev libegl1-mesa-dev libxcb-xinerama0-dev
      - name: Install Qt
        shell: bash
        run: |
          aqt install-qt linux desktop 6.6.0 gcc_64 -O ${{ runner.temp }}/Qt
          echo "${{ runner.temp }}/Qt/6.6.0/gcc_64/bin" >> $GITHUB_PATH
      - name: Configure and Build
        run: |
          mkdir build && cd build
          qmake ../TicTacToe_With_Tests/TicTacToe_With_Tests.pro
          make
      - name: Run Tests
        run: ./build/TicTacToe_With_Tests/tests/tests

  # Job for Windows
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install aqtinstall
      - name: Install Qt
        shell: bash
        run: aqt install-qt windows desktop 6.6.0 win64_msvc2019_64 -O C:/Qt
      # This action correctly sets up the MSVC compiler environment
      - name: Configure and Build
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          toolset: 14.29 # For VS2019
      - name: Build and Test
        shell: powershell
        run: |
          $env:Path = "C:\Qt\6.6.0\msvc2019_64\bin;" + $env:Path
          mkdir build
          cd build
          qmake ..\TicTacToe_With_Tests\TicTacToe_With_Tests.pro
          nmake
          .\TicTacToe_With_Tests\tests\release\tests.exe

  # Job for macOS
  build_macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install aqtinstall
      - name: Install Qt
        shell: bash
        run: |
          aqt install-qt mac desktop 6.6.0 clang_64 -O ${{ runner.temp }}/Qt
          echo "${{ runner.temp }}/Qt/6.6.0/macos/bin" >> $GITHUB_PATH
      - name: Configure, Build, and Test
        run: |
          mkdir build && cd build
          qmake ../TicTacToe_With_Tests/TicTacToe_With_Tests.pro
          make
      - name: Run Tests
        run: ./build/TicTacToe_With_Tests/tests/tests
